import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Onest, Unbounded } from "next/font/google";
import Script from "next/script";
import "./globals.css";
import Footer from "@/widgets/footer/ui/footer";
import { Providers } from "./providers";

const onest = Onest({
  variable: "--font-unbounded",
  subsets: ["latin", "cyrillic"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${onest.className} ${geistMono.variable} antialiased dark`}
      suppressHydrationWarning
    >
      <head>
        <Script
          src="https://telegram.org/js/telegram-web-app.js"
          strategy="beforeInteractive"
        />
      </head>
      <body className="h-dvh w-full flex flex-col overflow-hidden bg-zinc-950">
        <Providers>
          <main className="flex-1 flex flex-col min-h-0 overflow-y-auto overflow-x-hidden relative">
            {children}
          </main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
